apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.2.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.2.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.2.0
    spec:
      containers:
        - image: reg.dnt:5000/google_containers/heapster:v1.2.0
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          command:
            - /heapster
            - --source=kubernetes:http://20.26.2.110:18080
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: reg.dnt:5000/google_containers/heapster:v1.2.0
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          command:
            - /eventer
            - --source=kubernetes:http://20.26.2.110:18080
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: reg.dnt:5000/google_containers/addon-resizer:1.6
          name: heapster-nanny
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=200m
            - --extra-cpu=0m
            - --memory=500Mi
            - --extra-memory=100Mi
            - --threshold=5
            - --deployment=heapster-v1.2.0
            - --container=heapster
            - --poll-period=300000
        - image: reg.dnt:5000/google_containers/addon-resizer:1.6
          name: eventer-nanny
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=500m
            - --extra-cpu=0m
            - --memory=500Mi
            - --extra-memory=100Mi
            - --threshold=5
            - --deployment=heapster-v1.2.0
            - --container=eventer
            - --poll-period=300000
