apiVersion: v1
kind: Service
metadata: 
  name: prometheus-svc
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 80
    targetPort: 9090 
    name: prometheus
  - port: 3000
    targetPort: 3000
    name: grafana
