apiVersion: v1
kind: Pod
metadata:
  name: etcd-server
  namespace: system
  labels:
    app: "etcd-server"
    enable: "true"
    service: "base"
spec:
  hostNetwork: true
  containers:
  - image: gcr.io/coreos/etcd:v3.0.17
    name: etcd-container
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/etcd --name $NAME --initial-advertise-peer-urls http://$ADDR:7001 --listen-peer-urls http://$ADDR:7001 --advertise-client-urls http://$ADDR:4001 --listen-client-urls http://0.0.0.0:4001 --data-dir /var/etcd/data --initial-cluster-token etcd123456 --initial-cluster-state new --initial-cluster master1=http://$MASTER1:7001,master2=http://$MASTER2:7001,master3=http://$MASTER3:7001 1>>/var/log/etcd.log 2>&1
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    livenessProbe:
      httpGet:
        path: /version
        port: 4001
      initialDelaySeconds: 30
      timeoutSeconds: 30
    env:
    - name: NAME
      value: master3
    - name: ADDR
      value: 20.26.28.85
    - name: MASTER1
      value: 20.26.28.83
    - name: MASTER2
      value: 20.26.28.84
    - name: MASTER3
      value: 20.26.28.85
    volumeMounts:
    - mountPath: /var/etcd
      name: varetcd
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    - mountPath: /usr/share/ssl
      name: usrsharessl
      readOnly: true
    - mountPath: /var/ssl
      name: varssl
      readOnly: true
    - mountPath: /usr/ssl
      name: usrssl
      readOnly: true
    - mountPath: /usr/lib/ssl
      name: usrlibssl
      readOnly: true
    - mountPath: /usr/local/openssl
      name: usrlocalopenssl
      readOnly: true
    - mountPath: /etc/openssl
      name: etcopenssl
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etcpkitls
      readOnly: true
    - mountPath: /var/log/etcd.log
      name: logfile
  volumes:
  - hostPath:
      path: /data/etcd/data
    name: varetcd
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /usr/share/ssl
    name: usrsharessl
  - hostPath:
      path: /var/ssl
    name: varssl
  - hostPath:
      path: /usr/ssl
    name: usrssl
  - hostPath:
      path: /usr/lib/ssl
    name: usrlibssl
  - hostPath:
      path: /usr/local/openssl
    name: usrlocalopenssl
  - hostPath:
      path: /etc/openssl
    name: etcopenssl
  - hostPath:
      path: /etc/pki/tls
    name: etcpkitls
  - hostPath:
      path: /data/logs/base/etcd.log
    name: logfile
