apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: system
  labels:
    app: kube-proxy
    enable: "true"
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: reg.dnt:5000/google_containers/kube-proxy:v1.4.0
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-proxy --master=http://10.78.198.74:18080 --proxy-mode=iptables 1>>/var/log/kube-proxy.log 2>&1
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    volumeMounts:
    - mountPath: /var/log/kube-proxy.log
      name: logfile
  volumes:
  - hostPath:
      path: /data/log/kube-proxy.log
    name: logfile
