apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: system
  labels:
    app: "kube-proxy"
    enable: "true"
    service: "base"
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: reg.dnt:5000/google_containers/kube-proxy:v1.4.0
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-proxy --master=$ETCD_INFO --proxy-mode=iptables 1>>/var/log/kube-proxy.log 2>&1
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    env:
    - name: ETCD_INFO
      value: "http://10.78.198.74:18080" 
    volumeMounts:
    - mountPath: /var/log/kube-proxy.log
      name: logfile
  volumes:
  - hostPath:
      path: /data/logs/base/kube-proxy.log
    name: logfile
