apiVersion: v1
kind: Pod
metadata:
  name: haproxy-keepalived
  namespace: system
  labels: 
    app: "haproxy-keepalived"
    enable: "true"
    service: "base"
spec:
  hostNetwork: true
  securityContext:
    privileged: true
  containers:
  - name: haproxy
    image: reg.dnt:5000/haproxy:20161016
    command: 
    - /usr/local/sbin/haproxy
    - -p 
    - /run/haproxy.pid
    - -f
    - /etc/haproxy/haproxy.cfg
    - -d
    resources:
      limits:
        cpu: 2000m
        memory: 4096Mi
      requests:
        cpu: 1000m
        memory: 2048Mi
    volumeMounts:
    - mountPath: /etc/haproxy/haproxy.cfg
      name: haproxy-cfg
      readOnly: true
  - name: keepalived
    image: reg.dnt:5000/keepalived:20161016
    securityContext:
      privileged: true
    command:
    - /bin/bash
    - -c
    - /entrypoint.sh
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi
    volumeMounts:
    - mountPath: /etc/keepalived
      name: keepalived-cfg
      readOnly: true
    - mountPath: /entrypoint.sh
      name: entrypoint
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/haproxy/haproxy.cfg
    name: haproxy-cfg
  - hostPath:
      path: /etc/keepalived
    name: keepalived-cfg
  - hostPath:
      path: /etc/keepalived/entrypoint.sh
    name: entrypoint
